<a href="https://colab.research.google.com/github/parthsharma5575/Ai-Ml-GenAi/blob/main/BookRecommSystem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Book Recommendation System
Parth Sharma

35720802723

4th year cse

In [1]:
#Import libraries
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

[Dataset Link Here](https://www.kaggle.com/datasets/abdallahwagih/books-dataset)

In [2]:
#Dataset Load
df=pd.read_csv('/content/drive/MyDrive/Collab/bookdata.csv')

In [3]:
df.head()

,isbn13,isbn10,title,subtitle,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count
0,9780002005883,0002005883,Gilead,NaN,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0
1,9780002261982,0002261987,Spider's Web,A Novel,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0
2,9780006163831,0006163831,The One Tree,NaN,Stephen R. Donaldson,American fiction,http://books.google.com/books/content?id=OmQaw...,Volume Two of Stephen Donaldson's acclaimed se...,1982.0,3.97,479.0,172.0
3,9780006178736,0006178731,Rage of angels,NaN,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0
4,9780006280897,0006280897,The Four Loves,NaN,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0

In [4]:
df.shape

(6810, 12)

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6810 entries, 0 to 6809
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   isbn13          6810 non-null   int64
 1   isbn10          6810 non-null   object
 2   title           6810 non-null   object
 3   subtitle        2381 non-null   object
 4   authors         6738 non-null   object
 5   categories      6711 non-null   object
 6   thumbnail       6481 non-null   object
 7   description     6548 non-null   object
 8   published_year  6804 non-null   float64
 9   average_rating  6767 non-null   float64
 10  num_pages       6767 non-null   float64
 11  ratings_count   6767 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 638.6+ KB

In [7]:
df.isnull().sum()

isbn13               0
isbn10               0
title                0
subtitle          4429
authors             72
categories          99
thumbnail          329
description        262
published_year       6
average_rating      43
num_pages           43
ratings_count       43
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6810 entries, 0 to 6809
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   isbn13          6810 non-null   int64
 1   isbn10          6810 non-null   object
 2   title           6810 non-null   object
 3   subtitle        2381 non-null   object
 4   authors         6738 non-null   object
 5   categories      6711 non-null   object
 6   thumbnail       6481 non-null   object
 7   description     6548 non-null   object
 8   published_year  6804 non-null   float64
 9   average_rating  6767 non-null   float64
 10  num_pages       6767 non-null   float64
 11  ratings_count   6767 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 638.6+ KB

In [9]:
df.isnull().sum()

isbn13               0
isbn10               0
title                0
subtitle          4429
authors             72
categories          99
thumbnail          329
description        262
published_year       6
average_rating      43
num_pages           43
ratings_count       43
dtype: int64

In [10]:
df.fillna(' ',inplace=True)

/tmp/ipykernel_2618/3017097809.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' ' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.fillna(' ',inplace=True)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6810 entries, 0 to 6809
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   isbn13          6810 non-null   int64
 1   isbn10          6810 non-null   object
 2   title           6810 non-null   object
 3   subtitle        6810 non-null   object
 4   authors         6810 non-null   object
 5   categories      6810 non-null   object
 6   thumbnail       6810 non-null   object
 7   description     6810 non-null   object
 8   published_year  6810 non-null   object
 9   average_rating  6810 non-null   object
 10  num_pages       6810 non-null   object
 11  ratings_count   6810 non-null   object
dtypes: int64(1), object(11)
memory usage: 638.6+ KB

Merge Columns

In [12]:
books=df[['title','authors','subtitle','categories','description','average_rating','published_year']]

In [13]:
books.head()

,title,authors,subtitle,categories,description,average_rating,published_year
0,Gilead,Marilynne Robinson,,Fiction,A NOVEL THAT READERS and critics have been eag...,3.85,2004.0
1,Spider's Web,Charles Osborne;Agatha Christie,A Novel,Detective and mystery stories,A new 'Christie for Christmas' -- a full-lengt...,3.83,2000.0
2,The One Tree,Stephen R. Donaldson,,American fiction,Volume Two of Stephen Donaldson's acclaimed se...,3.97,1982.0
3,Rage of angels,Sidney Sheldon,,Fiction,"A memorable, mesmerizing heroine Jennifer -- b...",3.93,1993.0
4,The Four Loves,Clive Staples Lewis,,Christian life,Lewis' work on the nature of love divides love...,4.15,2002.0

In [14]:
books=books.copy()
books['content']=books['title']+' '+books['subtitle']+' '+books['authors']+' '+books['categories']+' '+books['description']

In [15]:
tfid=TfidfVectorizer(stop_words='english',max_features=5000)

In [16]:
tfid_matrix=tfid.fit_transform(books['content'])

In [17]:
similarity=cosine_similarity(tfid_matrix)

In [18]:
similarity

array([[1.        , 0.00569211, 0.00291048, ..., 0.        , 0.01214204,
        0.        ],
       [0.00569211, 1.        , 0.02085471, ..., 0.        , 0.00518251,
        0.03939511],
       [0.00291048, 0.02085471, 1.        , ..., 0.        , 0.01367924,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.01214204, 0.00518251, 0.01367924, ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.03939511, 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [29]:
from difflib import get_close_matches

def recommend(bookname,n=10):
  idx=books[books['title'].str.lower()==bookname.lower()].index
  #if not exact match
  recomm=[]
  if len(idx)==0:
    closest=get_close_matches(bookname,books['title'].tolist(),n=1,cutoff=0.6)
    if len(closest)==0:
      return 'Book Not Found'
    print(f"Book not found.\nShowing results for '{closest[0]}'")
    idx=books[books['title']==closest[0]].index

  idx=idx[0]
  distances=list(enumerate(similarity[idx]))
  distances=sorted(distances,key=lambda x:x[1],reverse=True)


  for i in distances[1:n+1]:
    recomm.append([books.iloc[i[0]].title,
                  books.iloc[i[0]].authors,
                  books.iloc[i[0]].categories,
                  books.iloc[i[0]].description]
                  )
  return pd.DataFrame(recomm,columns=[['Title','Authors','Categories','Description']])

In [35]:
name=input('Enter Book Name : ')
display(recommend(name))

Enter Book Name : harry potter

,Title,Authors,Categories,Description
0,The Harry Potter Collection,J. K. Rowling,Juvenile Fiction,The first six years of Harry Potter magic are ...
1,Harry Potter and the Prisoner of Azkaban (Book 3),"Rowling, J.K.",Juvenile Fiction,"For twelve long years, the dread fortress of A..."
2,Harry Potter and the Chamber of Secrets,J. K. Rowling;Mary GrandPre,Juvenile Fiction,When the Chamber of Secrets is opened again at...
3,Harry Potter and the Chamber of Secrets (Book 2),"Rowling, J.K.",Juvenile Fiction,"In Harry Potter and the Chamber of Secrets, th..."
4,Harry Potter and the Sorcerer's Stone (Book 1),"Rowling, J.K.",Juvenile Fiction,"In Harry Potter and the Sorcerer's Stone, Harr..."
5,Harry Potter and the Goblet of Fire,J. K. Rowling,Juvenile Fiction,The summer holidays are dragging on and Harry ...
6,Harry Potter and the Order of the Phoenix (Boo...,"Rowling, J.K.",Juvenile Fiction,"In Harry Potter and the Order of the Phoenix, ..."
7,Harry Potter and the Prisoner of Azkaban,J. K. Rowling,England,Harry Potter is lucky to reach the age of thir...
8,Ultimate Unofficial Guide to the Mysteries of ...,Galadriel Waters;Astre Mithrandir,Literary Criticism,A guide to J.K. Rowling's first four Harry Pot...
9,Harry Potter and the Half-Blood Prince (Book 6),"Rowling, J.K.",Juvenile Fiction,When Harry Potter and the Half-Blood Prince op...